### ISSUE TITLE
Error: Unable to resolve action `okteto/apply@master`

### ISSUE THREAD

**Issue by geekyouth** [okteto/apply#4]
```
Error: Unable to resolve action `okteto/apply@master`, unable to find version `master`. Unable to resolve action `okteto/login@master`, unable to find version `master`. Unable to resolve action `okteto/namespace@master`, unable to find version `master`
```

**Comment by mauroavellaneda** [comment]
> ```
> Error: Unable to resolve action `okteto/apply@master`, unable to find version `master`. Unable to resolve action `okteto/login@master`, unable to find version `master`. Unable to resolve action `okteto/namespace@master`, unable to find version `master`
> ```

having exact the same problem

**Comment by mauroavellaneda** [comment]
Also, Error: Unable to resolve action `okteto/deploy-preview@master`, unable to find version `master`. Unable to resolve action `okteto/login@master`, unable to find version `master`

**Comment by rberrelleza** [comment]
closing since this action is now deprecated
